matrix:
  include:
    - dist: xenial
      language: python
      python:
      - '3.7'
      - '3.8'
      - '3.9'
      install:
      - pip install -r requirements-dev.txt
      - pip install -r requirements-test.txt
      - pip install .
      script:
      - scripts/test.sh
      deploy:
        - provider: pypi
          user: "__token__"
          password:
            secure: "NuvexcY2ENS7wSZmgOviY9OYq7U+ggv2Bu3hSY4WWtTbfhoIgdPFZf68DuE/u/RTiOLkRT8iGLAJTTrySzvEF4W064uMnn+av5Vmtf5Lffja6TY6yi2myY6/vXx3gY9ZS1ZSCz2vfiBPzUe2i42XiDg/DZH/W5O6kohesbKivlufVITAn0Ze5lw60XxY0QMbnm6bTrrq5OCaks6qHIuNqf0wrnzFbH8yllT/Onof6aSMTsZsoMOpRkGuquHKM8Xm0EN0VsJQqz3MqicyvRl2/VrNBLgW1isdByE420GgnAdg01fLgtnBvmbsfbtfRJ/JoXOqaJ6YGKT4HmyvVWL8Vmh5i0hw1/QaQJ6gkkKJeguWnONDmvMuQecm76zOCO78GCr9fJswspJ/6h59pADhcQUyaQA1YyaM1QUzkKFXj+3LezHV/wb6vQd5cAt8F+OH4ZO+s48uqPjuoNUSA3NDb0KEKyTZ7gWPWpPUPFqf75rMTM0jgiZUvLI1La0XA5lU3wkzf7T45GvOtGkvUNfmymn0xb973REA8xbo2putFdjNgxlzEnvdRjJONdUJWUJI2VkQOybX69OWOgxYgwyfseud+1JX2HRwIaJ+2m8kl4vn5poDMD2wS1hlADIu7pXIsBDpHxjyzLgTGxdzfYx1Ci8ywnx+DD8wMnXNcDexo40="
          skip_existing: true
          on:
            tags: true
          skip_cleanup: true
